// bench/todomvc/solid/src/App.jsx
import { createSignal, createMemo, For } from 'solid-js';
import { createStore } from 'solid-js/store';

export default function App() {
  const [todos, setTodos] = createStore([]);
  const [filter, setFilter] = createSignal('all');
  const [title, setTitle] = createSignal('');
  const [live, setLive] = createSignal(0);
  let nextId = 0;

  const visible = createMemo(() =>
    todos.filter((t) =>
      filter() === 'active' ? !t.done : filter() === 'done' ? t.done : true
    )
  );
  const active = createMemo(() => todos.filter((t) => !t.done).length);

  function addTodo() {
    if (!title()) return;
    setTodos(todos.length, { id: ++nextId, title: title(), done: false });
    setTitle('');
  }

  function onKeydown(e) {
    if (e.key === 'Enter') addTodo();
  }

  function toggle(id) {
    setTodos((t) => t.id === id, 'done', (d) => !d);
  }

  function remove(id) {
    setTodos((prev) => prev.filter((t) => t.id !== id));
  }

  function startLive() {
    setLive(0);
    let i = 0;
    const timer = setInterval(() => {
      setLive(++i);
      if (i >= 30) clearInterval(timer);
    }, 100);
  }

  return (
    <div class="todoapp">
      <h1>todos</h1>
      <div class="entry">
        <input
          id="new-todo"
          type="text"
          placeholder="What needs to be done?"
          value={title()}
          onInput={(e) => setTitle(e.target.value)}
          onKeyDown={onKeydown}
        />
        <button id="add-todo" onClick={addTodo}>Add</button>
      </div>
      <ul id="todo-list">
        <For each={visible()}>
          {(t) => (
            <li class={t.done ? 'done' : ''} data-id={t.id}>
              <input type="checkbox" checked={t.done} onChange={() => toggle(t.id)} />
              <span>{t.title}</span>
              <button class="destroy" onClick={() => remove(t.id)}>x</button>
            </li>
          )}
        </For>
      </ul>
      <footer>
        <span id="todo-count">{active()} items left</span>
        <button onClick={() => setFilter('all')}>All</button>
        <button onClick={() => setFilter('active')}>Active</button>
        <button onClick={() => setFilter('done')}>Done</button>
      </footer>
      <div class="live">
        <button id="start-live" onClick={startLive}>Start live</button>
        <span id="live-counter">{live()}</span>
      </div>
    </div>
  );
}

// bench/todomvc/svelte/src/App.svelte
<script>
  let todos = $state([]);
  let filter = $state('all');
  let title = $state('');
  let live = $state(0);
  let nextId = 0;

  const visible = $derived(
    todos.filter((t) =>
      filter === 'active' ? !t.done : filter === 'done' ? t.done : true
    )
  );
  const active = $derived(todos.filter((t) => !t.done).length);

  function addTodo() {
    if (!title) return;
    todos.push({ id: ++nextId, title, done: false });
    title = '';
  }

  function onKeydown(e) {
    if (e.key === 'Enter') addTodo();
  }

  function toggle(id) {
    const t = todos.find((t) => t.id === id);
    if (t) t.done = !t.done;
  }

  function remove(id) {
    const i = todos.findIndex((t) => t.id === id);
    if (i !== -1) todos.splice(i, 1);
  }

  function startLive() {
    live = 0;
    let i = 0;
    const timer = setInterval(() => {
      live = ++i;
      if (i >= 30) clearInterval(timer);
    }, 100);
  }
</script>

<div class="todoapp">
  <h1>todos</h1>
  <div class="entry">
    <input
      id="new-todo"
      type="text"
      placeholder="What needs to be done?"
      bind:value={title}
      onkeydown={onKeydown}
    />
    <button id="add-todo" onclick={addTodo}>Add</button>
  </div>
  <ul id="todo-list">
    {#each visible as t (t.id)}
      <li class={t.done ? 'done' : ''} data-id={t.id}>
        <input type="checkbox" checked={t.done} onchange={() => toggle(t.id)} />
        <span>{t.title}</span>
        <button class="destroy" onclick={() => remove(t.id)}>x</button>
      </li>
    {/each}
  </ul>
  <footer>
    <span id="todo-count">{active} items left</span>
    <button onclick={() => (filter = 'all')}>All</button>
    <button onclick={() => (filter = 'active')}>Active</button>
    <button onclick={() => (filter = 'done')}>Done</button>
  </footer>
  <div class="live">
    <button id="start-live" onclick={startLive}>Start live</button>
    <span id="live-counter">{live}</span>
  </div>
</div>
